# Generated by Django 2.0.1 on 2018-06-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFiles',
            fields=[
                ('file_number', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=50)),
                ('content', models.FileField(upload_to='')),
                ('thumnail', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
