# Generated by Django 2.0.1 on 2018-06-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcoin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedfiles',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
