# Generated by Django 2.0.1 on 2018-06-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcoin', '0002_auto_20180606_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedfiles',
            name='content',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/content'),
        ),
        migrations.AlterField(
            model_name='storedfiles',
            name='thumnail',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/thumnail'),
        ),
    ]
