# Generated by Django 2.0.1 on 2018-06-08 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('redcoin', '0003_auto_20180606_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfiles',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storedfiles',
            name='content',
            field=models.FileField(upload_to='%Y/%m/%d/content'),
        ),
        migrations.AlterField(
            model_name='storedfiles',
            name='thumnail',
            field=models.ImageField(upload_to='%Y/%m/%d/thumnail'),
        ),
    ]
